/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AnionChatBubble {
    /**
    * The display name associated with the chat message.
    */
    'author': string;
    /**
    * The side where the avatar should appear.
    */
    'avatarSide': 'left' | 'right';
    /**
    * The URL for the image source of the avatar.
    */
    'avatarUrl': string;
  }
  interface AnionChatBubbleAttributes extends StencilHTMLAttributes {
    /**
    * The display name associated with the chat message.
    */
    'author'?: string;
    /**
    * The side where the avatar should appear.
    */
    'avatarSide'?: 'left' | 'right';
    /**
    * The URL for the image source of the avatar.
    */
    'avatarUrl'?: string;
  }

  interface AnionChipBar {
    /**
    * Add a chip to the bar.
    */
    'addChip': (chipText: string) => Promise<void>;
    /**
    * Color name of the ion-chip components.
    */
    'chipColor': string;
    /**
    * Remove all chips from the bar.
    */
    'clearChips': () => Promise<void>;
    /**
    * Default set of chips to appear in the bar.
    */
    'defaultChips': string;
    /**
    * Get the chips currently in the bar.
    */
    'getChips': () => Promise<string[]>;
    /**
    * Remove a chip from the bar.
    */
    'removeChip': (chipText: string) => Promise<void>;
    /**
    * Set the chips in the bar. Note: any existing chips are cleared first.
    */
    'setChips': (chipTexts: string[]) => Promise<void>;
  }
  interface AnionChipBarAttributes extends StencilHTMLAttributes {
    /**
    * Color name of the ion-chip components.
    */
    'chipColor'?: string;
    /**
    * Default set of chips to appear in the bar.
    */
    'defaultChips'?: string;
    /**
    * Emitted when a chip is removed.
    */
    'onAnionChipRemoved'?: (event: CustomEvent) => void;
  }

  interface AnionChipInputbar {
    /**
    * Add a chip to the bar.
    */
    'addChip': (chipText: string) => Promise<void>;
    /**
    * Color name of the ion-chip components.
    */
    'chipColor': string;
    /**
    * Remove all chips from the bar.
    */
    'clearChips': () => Promise<void>;
    /**
    * Clear the text of the input element.
    */
    'clearText': () => Promise<void>;
    /**
    * Get the chips current in the bar.
    */
    'getChips': () => Promise<string[]>;
    /**
    * The placeholder text of the input element.
    */
    'inputPlaceholder': string;
    /**
    * The text of the associated inputbar label.
    */
    'labelText': string;
    /**
    * Remove a chip from the bar.
    */
    'removeChip': (chipText: string) => Promise<void>;
    /**
    * Set the chips in the bar. Note: any existing chips are cleared first.
    */
    'setChips': (chipTexts: string[]) => Promise<void>;
    /**
    * Set focus on the input element.
    */
    'setFocus': () => Promise<void>;
  }
  interface AnionChipInputbarAttributes extends StencilHTMLAttributes {
    /**
    * Color name of the ion-chip components.
    */
    'chipColor'?: string;
    /**
    * The placeholder text of the input element.
    */
    'inputPlaceholder'?: string;
    /**
    * The text of the associated inputbar label.
    */
    'labelText'?: string;
    /**
    * Emitted when the value of the input element is changed.
    */
    'onAnionInputChange'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AnionChatBubble': Components.AnionChatBubble;
    'AnionChipBar': Components.AnionChipBar;
    'AnionChipInputbar': Components.AnionChipInputbar;
  }

  interface StencilIntrinsicElements {
    'anion-chat-bubble': Components.AnionChatBubbleAttributes;
    'anion-chip-bar': Components.AnionChipBarAttributes;
    'anion-chip-inputbar': Components.AnionChipInputbarAttributes;
  }


  interface HTMLAnionChatBubbleElement extends Components.AnionChatBubble, HTMLStencilElement {}
  var HTMLAnionChatBubbleElement: {
    prototype: HTMLAnionChatBubbleElement;
    new (): HTMLAnionChatBubbleElement;
  };

  interface HTMLAnionChipBarElement extends Components.AnionChipBar, HTMLStencilElement {}
  var HTMLAnionChipBarElement: {
    prototype: HTMLAnionChipBarElement;
    new (): HTMLAnionChipBarElement;
  };

  interface HTMLAnionChipInputbarElement extends Components.AnionChipInputbar, HTMLStencilElement {}
  var HTMLAnionChipInputbarElement: {
    prototype: HTMLAnionChipInputbarElement;
    new (): HTMLAnionChipInputbarElement;
  };

  interface HTMLElementTagNameMap {
    'anion-chat-bubble': HTMLAnionChatBubbleElement
    'anion-chip-bar': HTMLAnionChipBarElement
    'anion-chip-inputbar': HTMLAnionChipInputbarElement
  }

  interface ElementTagNameMap {
    'anion-chat-bubble': HTMLAnionChatBubbleElement;
    'anion-chip-bar': HTMLAnionChipBarElement;
    'anion-chip-inputbar': HTMLAnionChipInputbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
